kind: pipeline
type: docker
name: default

steps:
  - name: build1
    image: kaniko
    pull: if-not-exists
    settings:
      registry: registry:5000
      repo: my/repo
      extra_opts: --insecure --insecure-pull
    volumes:
      - name: cache
        path: /cache
  - name: build2
    image: kaniko
    pull: if-not-exists
    settings:
      registry: registry:5000
      repo: my/repo
      extra_opts: --insecure --insecure-pull
    volumes:
      - name: cache
        path: /cache
  - name: cleanup
    image: alpine
    commands:
      - rm kaniko.*

services:
  - name: registry
    image: registry:2

volumes:
  - name: cache
    temp: {}
